# Adopted from https://github.com/GokuMohandas/Made-With-ML
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: "notebooks|data|venv|scratch"
-   repo: local
    hooks:
    -   id: clean
        name: clean
        entry: make
        args: ["clean"]
        language: system
        pass_filenames: false
        exclude: "venv"
# Clean up notebooks output and metadata
-   repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
    -   id: nb-clean
        exclude: "venv"
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: "venv"
